site_name: stac-cog-xarray
site_url: https://hrodmn.github.io/stac-cog-xarray/
repo_url: https://github.com/hrodmn/stac-cog-xarray
repo_name: hrodmn/stac-cog-xarray

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy

extra_css:
  - stylesheets/extra.css

nav:
  - Introduction: index.md
  - Demo: demo.ipynb
  - Architecture: architecture.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
  - mkdocs-jupyter:
      execute: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
